# Introduzione a PyTorch

Author: Nicola Arici (nicola.arici@unibs.it)

## **What is PyTorch?**

PyTorch is an open-source deep learning framework developed by Facebook’s AI Research team (FAIR). It's particularly popular for its flexibility and usability in research and production alike. Unlike TensorFlow's older versions, which used static computation graphs, PyTorch uses dynamic computation graphs, making it easier to debug and more intuitive for Python programmers.

In this notebook, we will explore PyTorch's key features, followed by comparisons to Keras and TensorFlow.

**Resources**

- [PyTorch Documentation](https://pytorch.org/docs/)
- [Keras Documentation](https://keras.io/)


<br>

## **Installing PyTorch**

Since we're on Colab, we have nothing to do.
But if you are interested in running it locally, you can follow the instructions from [PyTorch's official website](https://pytorch.org/get-started/locally/) to choose the correct version for CPU or GPU.


```bash
pip install torch torchvision torchaudio
```



---

### **Tensors: The Building Block of PyTorch**

In PyTorch, tensors are the fundamental data structure, analogous to arrays in NumPy but with the added advantage that they can run on GPUs. In this section, we’ll explore various ways to create tensors and some basic operations that can be performed on them.

In [30]:
import torch
import numpy as np

DATA = [[1.0, 2.0], [3.0, 4.0]]

np_array = np.array(DATA)
print(f"NumPy array: \n {np_array}")

tensor_from_list = torch.tensor(DATA)
print(f"\nTensor from list:\n {tensor_from_list}")

tensor_from_numpy = torch.from_numpy(np_array)
print(f"\nTensor from NumPy array:\n {tensor_from_numpy}")


NumPy array: 
 [[1. 2.]
 [3. 4.]]

Tensor from list:
 tensor([[1., 2.],
        [3., 4.]])

Tensor from NumPy array:
 tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


**Creating Tensors with Special Initialization**

PyTorch provides several functions to create tensors with specific initial values.

In [ ]:
# Creating a tensor of zeros
zeros_tensor = torch.zeros((2, 3))
print(f"Tensor of zeros:\n {zeros_tensor}")

# Creating a tensor of ones
ones_tensor = torch.ones((2, 3))
print(f"\nTensor of ones:\n {ones_tensor}")

# Creating a tensor with random values
random_tensor = torch.rand((2, 3))
print(f"\nRandom tensor:\n {random_tensor}")

rand_like_tensor = torch.rand_like(random_tensor)
print(f"\nRandom tensor with the same shape as the previous tensor:\n {rand_like_tensor}")

**Moving Tensors Between Devices (CPU and GPU)**

One of the key advantages of PyTorch is its seamless support for GPU acceleration. PyTorch allows tensors to be created on or moved between devices like CPUs and GPUs. This is done using the ```torch.device()``` object and the ```to()``` method. If a GPU is available, computations *can* be much faster.

In [ ]:
from time import time

# Check if GPU is available
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

tensor_on_gpu = torch.rand((2, 3), )
print("Tensor on GPU (if available):\n", tensor_on_gpu)


# Moving a tensor from CPU to GPU
tensor_cpu = torch.ones((2, 3))

s = time()
result = tensor_cpu ** 2 * tensor_cpu ** 5
print(f"\nTime taken on CPU: {round((time() - s)*1000, 6)} ms")

tensor_gpu =
s = time()
result = tensor_gpu ** 2 * tensor_gpu ** 5
print(f"Time taken on GPU: {round((time() - s)*1000, 6)} ms")


---

### **Automatic Differentiation: PyTorch’s Autograd**

In deep learning, we often need to calculate gradients during backpropagation to update the weights of a neural network. [PyTorch’s autograd module](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html) is responsible for automatically computing the gradients of tensors during the backward pass. It does this by building a [dynamic computational graph](https://pytorch.org/blog/computational-graphs-constructed-in-pytorch/), where nodes represent operations and edges represent the flow of data.

PyTorch tracks every operation on tensors with ```requires_grad=True``` to enable automatic differentiation.


In [ ]:
import torch

x = torch.tensor([2.0, 3.0], )

y = x[0] ** 3 + x[1] * 2

print(f"Results: {y} \n")

print(f"Gradients of x: {x.}")
print(f"Backward Function of y: {y.}")

In [ ]:
# Create a tensor with requires_grad=True
a = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

# Perform operations with gradient tracking
s = time()
b = a ** 2
print(f"With gradient tracking {round((time() - s)*1000, 6)} ms")

# Disable gradient tracking
with \:
    s = time()
    c = a ** 2
    print(f"Without gradient tracking {round((time() - s)*1000, 6)} ms")



---

### **Building a Simple Neural Network in PyTorch**

In this section, we will walk through the process of creating a simple neural network using PyTorch. All the components needed to build the network are contained in the [torch.nn](https://pytorch.org/docs/stable/nn.html) package.

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

INPUT = np.array([[1.0, 2.0]])

# Define a simple network using Keras
model = Sequential([
    Input((2,)),
    Dense(4, activation='relu'),
    Dense(1)
])

print(model.summary())

s = time()
print(f"\nForward Pass: {model.predict(INPUT)} in {round((time() - s)*1000, 6)} ms")

Exception ignored in: <function _xla_gc_callback at 0x7f1d2d19e3e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/jax/_src/lib/__init__.py", line 96, in _xla_gc_callback
    def _xla_gc_callback(*args):
    
KeyboardInterrupt: 


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17 (68.00 B)

 Trainable params: 17 (68.00 B)

 Non-trainable params: 0 (0.00 B)

None
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 491ms/step

Forward Pass: [[-1.2210001]] in 542.734861 ms


In [27]:
import torch
import torch.nn as nn
import torch.optim as optim

INPUT = torch.tensor([[1.0, 2.0]])

net = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)

print(net)

s = time()
print(f"\nForward Pass: {net(INPUT)} in {round((time() - s)*1000, 6)} ms")

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
)

Forward Pass: tensor([[0.2261]], grad_fn=<AddmmBackward0>) in 56.472063 ms


PyTorch neural networks are typically defined by subclassing torch.nn.Module, which represents a base class for all neural networks in PyTorch. Layers are defined in the ```__init__()``` method, and the forward pass is implemented in the ```forward()``` method.

In [ ]:
class SimpleNet(nn.Module):

  def __init__(self):
    super(SimpleNet, self).__init__()

    self.linear1 = nn.linear(2,4)
    self.linear2 = nn.linear(4,1)

    self.relu = nn.ReLU()


  def forward(self, x):

   # return self.linear2(self.relu(self.linear1(x))) # x viene passato da dentro a fuori della rete. Ma questa modalità è scomoda

   h = self.relu(self.linear1(x)) # h == hidden
   o = self.linear2(h)            # o == output

   return o

net = SimpleNet()

print(net)

s = time()
print(f"\nForward Pass: {net(INPUT)} in {round((time() - s)*1000, 6)} ms")

**Training a Neural Network in PyTorch**

PyTorch is a powerful deep learning library that gives us a high degree of manual control over every step of the training process. Unlike Keras, which abstracts many of the internal workings behind easy-to-use functions, PyTorch allows us to customize every part of the model’s behavior. This can be especially useful when we need to fine-tune specific aspects of the training or modify the underlying logic to fit complex or non-standard tasks.

We will begin by setting up a basic neural network model, define the [loss function](https://pytorch.org/docs/stable/nn.html#loss-functions), and then proceed with training the network on a dataset. As we go, we'll manually implement essential components such as forward passes, backpropagation, and weight updates with [optimizer](https://pytorch.org/docs/stable/optim.html).

In [ ]:
# Define loss function and optimizer

net = SimpleNet()

criterion =
optimizer =

# Train the network to understand if the input is positive or negative

train_dataset = [
    (torch.tensor([1.0, 2.0]), torch.tensor([1.0])),
    (torch.tensor([-3.0, -4.0]), torch.tensor([0.0])),
    (torch.tensor([5.0, 6.0]), torch.tensor([1.0])),
    (torch.tensor([-5.0, -6.0]), torch.tensor([0.0])),
]

NUM_EPOCHS = 5

for epoch in range(NUM_EPOCHS):
    for tensor, target in train_dataset:


    print(f"Epoch {epoch+1}, Loss: {round(loss.item(), 4)}")

## **PyTorch vs. TensorFlow/Keras**


| Feature               | PyTorch                                    | TensorFlow/Keras                          |
|-----------------------|--------------------------------------------|-------------------------------------------|
| **API Level**          | Low-level, very flexible                   | High-level (Keras) or low-level (TF core) |
| **Computation Graph**  | Dynamic (eager execution)                  | Dynamic (with TensorFlow 2.x)             |
| **Ease of Use**        | More manual, but powerful                  | Keras is very user-friendly               |
| **Community**          | Growing rapidly, dominant in research      | Strong support, widely adopted in industry|
| **Ecosystem**          | Fewer add-ons (though fast-growing)        | Large ecosystem (e.g., TensorFlow Hub)    |

<br>

## **Conclusion**

- PyTorch provides exceptional flexibility, making it a favorite for researchers.
- TensorFlow has a mature ecosystem, but PyTorch’s dynamic nature is great for debugging and custom models.
- Keras is best for beginners or when rapid prototyping is necessary.

